### ISSUE TITLE
Google Maps Not Functioning With Locations On Events

### ISSUE THREAD

**Issue by JMSolo** [offiria/offiria#4]
Upon the creation of events with locations the submission of the "Share" button results in a stall in the update process - result is neither a failed event share.. nor a successful.  The process just doesn't complete.

Creating Events without locations result in successful shares.

Still no solution has been found for this.

Typical System Specs::

PHP Version:    5.3.27
Web Server: Apache/2.2.22 (Unix) mod_hive/3.6 mod_ssl/2.2.22 OpenSSL/1.0.0-fips mod_bwlimited/1.4
Joomla! Version:    Joomla! 2.5.14 Stable [ Ember ] 01-August-2013 14:00 GMT 

Furthermore; the process of locations renders the very same results for previous joomla version initially packaged with Offiria GitHub bundle.

![nomap-office-2](https://f.cloud.github.com/assets/5215074/961837/e42e6dcc-04e2-11e3-9dd6-de9bdfe51164.png)

**Comment by offiria** [comment]
Can someone verify this? Working ok in our local copy

**Comment by JMSolo** [comment]
Just to verify.. these are the specs and additional information for our setup currently exhibiting errors for the maps.

PHP Version --->    5.3.27
Web Server --->     Apache/2.2.22
Joomla! Version --->    Joomla! 2.5.14 Stable

I am seeing more push towards updating Offiria to work better with 2.5.14.  I am wondering if this may be an issue seeing as how I went ahead and updated joomla!  Although, that push is nothing more than matching up the changes between old joomla instances and current. 

Also, we are running an instance on a sub-domain, ie; http://offiria.domain.com/offiriaoffice
I am curious if this may be producing some anomaly that creates the issue.  If you could be so kind to point us to the files that are calling up the google maps api for event posting then we can scan through and see what the problem may be.

Furthermore, only when trying to input a location on the map do we get an error such as what is posted below.  If we remove the location and make editions to the event.. no error occurs.
![0c21f1d4-1274-11e3-8979-aa4b0540e4a3](https://f.cloud.github.com/assets/5215074/1064582/18430fd6-133f-11e3-8072-dae909a7e3f3.jpg)

**Comment by JMSolo** [comment]
We tested this on a root install and the problem still persist.

**Comment by azrul** [comment]
php warning error. I've fixed it in my latest push and working fine on my end now.

**Comment by JMSolo** [comment]
Thanks azrul.  We'll check that out.

**Comment by JMSolo** [comment]
We have created a fresh install of Offiria with all updated commits.  The events locations are still not working. An example to see how they are not performing the correct actions can be seen within Offiria's very own Live Demo.
- Creating an event without location = works 
- Creating an event with location = load loop (not a php warning or error - tried on both PHP5.3 and 5.4 with same results)
- Editing an event already created by adding in location afterwards = Results exactly as those illustrated above.

We are still trying to sort this out but our schedules have become consumed with a new client.  We are hoping that others will step forward and share their findings and/or solutions.

Thanks for sharing thus far.

**Comment by offiria** [comment]
The demo does not have the latest code. This is working fine internally. I'll try and push the latest code to the demo site soon.

![company-wide_stream](https://f.cloud.github.com/assets/4747111/1082311/99546fea-1586-11e3-8633-570ae2918db5.png)

**Comment by JMSolo** [comment]
Thanks, somewhere I am missing something.  Could you be so kind as to send me the location and/or code that updates this function. If you wish, you may email me directly  (  jason (at) jmsolodesigns.com ).  I would love to get this sorted out.

**Comment by JMSolo** [comment]
The issue was indeed curl.  Hence I was plagued by the fact that I have it enabled on my server.  This pull fixed my map problems so this can be safely closed.  Thanks.

https://github.com/offiria/offiria/issues/58
